### ISSUE TITLE
Test run error after installation

### ISSUE THREAD

**Issue by BryanKoo** [SekouD/mlconjug#70]
* MLConjug version: 3.2.2
* Python version: 3.6.7
* Operating System: ubuntu 18.04.1

### Description
I installed the package using pip3.
When I run the command line I get error.
(running with python also not working)

### What I Did
$ mlconjug manger
Traceback (most recent call last):
  File "/usr/local/bin/mlconjug", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mlconjug/cli.py", line 18, in main
    conjugator = Conjugator(language)
  File "/usr/local/lib/python3.6/dist-packages/mlconjug/mlconjug.py", line 127, in __init__
    self.conjug_manager = ConjugManager(language=language)
  File "/usr/local/lib/python3.6/dist-packages/mlconjug/PyVerbiste.py", line 117, in __init__
    self._load_verbs(verbs_file)
  File "/usr/local/lib/python3.6/dist-packages/mlconjug/PyVerbiste.py", line 136, in _load_verbs
    with open(verbs_file, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/mlconjug/data/conjug_manager/verbs-fr.json'

**Comment by SekouD** [comment]
Hi @BryanKoo thanks for your report.

Do you still have your issue?

I tried to replicate the issue on Ubuntu but could not, the file verbs-fr.json is installed and found witout problem on my test machine.

Thank you.

**Comment by SekouD** [comment]
Hi @BryanKoo you should try the new version [v 3.2.3](https://pypi.org/project/mlconjug/), it fixes the bug that did not include the data files during installation.

Cheers.
